import Head from "next/head";
import Link from "next/link";
import Header from "./header";

const Layout: React.FunctionComponent = ({ children }) => {
  return (
    <div className="w-full px-8 pb-10">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="max-w-4xl mx-auto">{children}</main>
    </div>
  );
};

export default Layout;
