import Head from "next/head";
import Link from "next/link";

const Layout: React.FunctionComponent = ({ children }) => {
  return (
    <div className="w-full px-8 pb-10">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="max-w-4xl mx-auto py-4">
        <Link href="/" passHref>
          <div className="h-8 flex items-center space-x-2 cursor-pointer">
            <div className="font-medium">掘金小助手</div>
            <div className="text-gray-400 text-xs">扩展市场</div>
          </div>
        </Link>
      </header>
      <main className="max-w-4xl mx-auto">{children}</main>
    </div>
  );
};

export default Layout;
