name: Deploy Gitee Page
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        run: |
          npm run deploy

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          BRANCH: gh-pages
          FOLDER: out
