name: Deploy Gitee Page
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        run: |
          npm install
          npm run deploy

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        env:
          BRANCH: gh-pages
          FOLDER: out

      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v1.1.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:curly210102/juejin-enhancer-extensions.git
          destination-repo: git@gitee.com:curlly-brackets/juejin-enhancer-extensions.git
